id: IEEC3BA45
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:37:52+00:00'
last_modified: '2022-06-08T09:53:20.939943+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30086
  title: གུང་ཐང་བློ་གྲོས་རྒྱ་མཚོའི་བློ་རྟགས་ཀྱི་མཆན་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    94A2:
      image_group_id: I5796
      title: ''
      total_pages: 472
      order: 1
      base_file: 94A2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
