id: P009279
initial_creation_type: ocr
source_metadata:
  id: bdr:W30086
  title: གུང་ཐང་བློ་གྲོས་རྒྱ་མཚོའི་བློ་རྟགས་ཀྱི་མཆན་འགྲེལ།
  author: ''
  volumes:
    7a9f4c1369164781a8ef6f04f2d2943f:
      image_group_id: I5796
      title: ''
      volume_number: 1
      total_pages: 472
      base_file: v001.txt
